version: '3.7'
services:
  schedule-app:
    build: .
    ports:
      - "8910:80"
    volumes:
      - ./:/var/www
    depends_on:
      - schedule-mysql
      - schedule-redis

  schedule-mysql:
    image: mysql:5.7.22
    command: --innodb-use-native-aio=0
    restart: always
    ports:
      - '3310:3306'
    volumes:
      - scheduledb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: schedule
      MYSQL_ROOT_PASSWORD: root

  schedule-redis:
    image: redis:alpine
    expose:
      - '6379'

networks:
  default:
    external:
      name: tcc-network

volumes:
  scheduledb: