apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-mysql
  labels:
    app: user-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user-mysql
    spec:
      containers:
        - image: mysql:5.7
          args:
            - "--ignore-db-dir=lost+found"
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-mysql-secret
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: user-mysql-secret
                  key: database
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-user-pv-claim
