version: '3.7'
services:
  nonconformity-app:
    build: .
    ports:
      - "8900:80"
    volumes:
      - ./:/var/www
    depends_on:
      - nonconformity-mysql
      - nonconformity-redis

  nonconformity-mysql:
    image: mysql:5.7.22
    command: --innodb-use-native-aio=0
    restart: always
    ports:
      - '3307:3306'
    volumes:
      - nonconformitydb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nonconformity
      MYSQL_ROOT_PASSWORD: root

  nonconformity-redis:
    image: redis:alpine
    expose:
      - '6379'

networks:
  default:
    external:
      name: tcc-network

volumes:
  nonconformitydb: