apiVersion: v1
kind: ConfigMap
metadata:
  name: nc-app-conf
  labels:
    name: nc-app-conf
data:
  env: |
    APP_NAME=NCApi
    APP_ENV=local
    APP_KEY=
    APP_DEBUG=true
    APP_URL=http://localhost
    APP_TIMEZONE=America/Sao_Paulo
    
    LOG_CHANNEL=stack
    LOG_SLACK_WEBHOOK_URL=
    
    DB_CONNECTION=mysql
    DB_HOST=nc-mysql-service
    DB_PORT=3306
    
    CACHE_DRIVER=file
    QUEUE_CONNECTION=sync

    KAFKA_HOST="tcc-cp-kafka-headless"
    KAFKA_PORT="9092"