version: '3.7'
services:
  user-app:
    build: ./.docker
    volumes:
      - ./:/var/www
    depends_on:
      - user-mysql
      - user-redis

  user-mysql:
    image: mysql:5.7.22
    command: --innodb-use-native-aio=0
    restart: always
    ports:
      - '3308:3306'
    volumes:
      - userdb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: user-app
      MYSQL_ROOT_PASSWORD: root

  user-redis:
    image: redis:alpine
    expose:
      - '6379'

  user-nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8901:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    depends_on:
      - user-app

networks:
  default:
    external:
      name: tcc-network

volumes:
  userdb: