version: '3.7'
services:
  automotive_process-app:
    build: ./.docker
    volumes:
      - ./:/var/www
    depends_on:
      - automotive_process-mysql
      - automotive_process-redis

  automotive_process-mysql:
    image: mysql:5.7.22
    command: --innodb-use-native-aio=0
    restart: always
    ports:
      - '3309:3306'
    volumes:
      - automotive_processdb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: automotive_process
      MYSQL_ROOT_PASSWORD: root

  automotive_process-redis:
    image: redis:alpine
    expose:
      - '6379'

  automotive_process-nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8909:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    depends_on:
      - automotive_process-app

networks:
  default:
    external:
      name: tcc-network

volumes:
  automotive_processdb: